runtime: python311

entrypoint: python http_server.py

env_variables:
  PYTHONUNBUFFERED: "1"
  MALAYA_CACHE: "/tmp/.malaya"
  PORT: "8080"
  HOST: "0.0.0.0"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
