steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'malaylanguage-mcp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,PORT=8080,HOST=0.0.0.0,MALAYA_CACHE=/tmp/.malaya'

images:
  - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/malaylanguage-mcp:latest'

options:
  machineType: 'E2_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY
